### ISSUE TITLE
Consider merging with blesta-tastycpanel

### ISSUE THREAD

**Issue by extremeshok** [CyanDarkInc/cPanel-Extended#1]
Please consider merging/proting your fixes/additions to the blesta maintained tasteycpanel.

https://github.com/blesta/module-tastycpanel

Thanks

**Comment by CyanDarkInc** [comment]
Hi,
I updated the module and I ported some features from Tasty cPanel, For more information please read the following link.

http://www.blesta.com/forums/index.php?/topic/5552-module-cpanel-extended-v41/
